### ISSUE TITLE
stack.im Applicatoin Error

### ISSUE THREAD

**Issue by gutsal-arsen** [mdippery/stackim#4]
```
archer@capitan ~ $ curl -XPUT -d "stackid=198087" http://stack.im/me
<!DOCTYPE html>
	<html>
	  <head>
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html
```

**Comment by mdippery** [comment]
Yeah, unfortunately, the MongoDB host I was using closed up shop, and I haven't gotten around to finding a new one.

**Comment by gutsal-arsen** [comment]
Would you bother moving stuff to new MongoDB hosting if I help you finding appropriate one? I can for instance run MongoDB on my Heroku account for free for you.

**Comment by mdippery** [comment]
Thanks for the offer! It's not a money issue; I just haven't gotten around to updating the Heroku account with a new add-on. I'll try to take a look at this some weekend soon.

**Comment by gutsal-arsen** [comment]
Thank you. Let me know please.

**Comment by mdippery** [comment]
I have this rewritten to use PostgreSQL as a backend. I'll push the working version up to Heroku sometime this weekend.

**Comment by gutsal-arsen** [comment]
Unfortunatelly
```
capitan% curl -XPUT -d "stackid=198087" http://stack.im/me
ERROR: relation "tags" does not exist
  Position: 22%   
```

**Comment by mdippery** [comment]
Thanks. Yeah, I have a couple issues to work out before it's fully working again.

**Comment by gutsal-arsen** [comment]
Let me know please. I will try.

**Comment by mdippery** [comment]
Back in business once again!

**Comment by gutsal-arsen** [comment]
Some more logs as for 2017-09-23
```
curl -XPUT -d "stackid=198087" http://stack.im/me
OK
curl -XPUT -d "stackid=198087" http://stack.im/me
Tag 'me' is already in use                                                                                                                                                         ```

**Comment by mdippery** [comment]
That is working as expected. Once a shortcut has been created, you can't create another one with the same name.
